#include <assert.h>
#include "unity_fixture.h"
#include "unity.h"
#include "unity_memory.h"
#include "beacon.h"

TEST_GROUP(beacon);


TEST_SETUP(beacon) {
    UnityMalloc_StartTest(); // see unity/extras/memory/readme.md
}
TEST_TEAR_DOWN(beacon) {
    UnityMalloc_EndTest();
}
/*
               1    1    2    2
     0    5    0    5    0    5
-2 ..........#.................
-1 .........###................
 0 ....S...#####...............
 1 .......#######........S.....
 2 ......#########S............
 3 .....###########SB..........
 4 ....#############...........
 5 ...###############..........
 6 ..#################.........
 7 .#########S#######S#........
 8 ..#################.........
 9 ...###############..........
10 ....B############...........
11 ..S..###########............
12 ......#########.............
13 .......#######..............
14 ........#####.S.......S.....
15 B........###................
16 ..........#SB...............
17 ................S..........B
18 ....S.......................
19 ............................
20 ............S......S........
21 ............................
22 .......................B....

*/
TEST(beacon, excluded) {
    int sx=8; int sy=7; int bx=2; int by=10;
    TEST_ASSERT_TRUE(excluded(sx,sy,bx,by,2,10));
    TEST_ASSERT_FALSE(excluded(sx,sy,bx,by,1,11));
    TEST_ASSERT_TRUE(excluded(sx,sy,bx,by,1,9));
    TEST_ASSERT_TRUE(excluded(sx,sy,bx,by,16,8));
    TEST_ASSERT_TRUE(excluded(sx,sy,bx,by,8,7));
}

TEST(beacon, get_sensor) {
    int sx, sy, bx, by;
    get_sensor("Sensor at x=2, y=18: closest beacon is at x=-2, y=15", &sx, &sy, &bx, &by);
    TEST_ASSERT_EQUAL_INT(2,  sx);
    TEST_ASSERT_EQUAL_INT(18, sy);
    TEST_ASSERT_EQUAL_INT(-2, bx);
    TEST_ASSERT_EQUAL_INT(15, by);
}
